[package]
name = "timelapse"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]
edition = "2018"

[dependencies]
chrono = "0.4.15"
log = "0.4.11"
env_logger = "0.7.1"
actix-web = "3.0.2"
actix-files = "0.3.0"
clap = "3.0.0-beta.2"
